<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
	<PublishSingleFile>true</PublishSingleFile>
	<SelfContained>true</SelfContained>
	<RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <Nullable>enable</Nullable>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <ApplicationIcon>Assets\dboard_icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Assets\amongusbutt.png" />
    <None Remove="Assets\dboard_icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="ReadMeFiles\amongusbutt.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\dboard_icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AsyncImageLoader.Avalonia" Version="3.3.0" />
    <PackageReference Include="Avalonia" Version="11.1.3" />
    <PackageReference Include="Avalonia.AvaloniaEdit" Version="11.3.0" />
    <PackageReference Include="Avalonia.Controls.ColorPicker" Version="11.1.3" />
    <PackageReference Include="Avalonia.Desktop" Version="11.1.3" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.1.3" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.1.3" />
    <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
    <PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" Version="11.1.3" />
    <PackageReference Include="Avalonia.ReactiveUI" Version="11.1.3" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.3.0" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaXaml Update="Styles\Icons.axaml">
      <SubType>Designer</SubType>
    </AvaloniaXaml>
    <AvaloniaXaml Update="Styles\SettingsStyles.axaml">
      <SubType>Designer</SubType>
    </AvaloniaXaml>
    <AvaloniaXaml Update="Views\EdgeView.axaml">
      <SubType>Designer</SubType>
    </AvaloniaXaml>
    <AvaloniaXaml Update="Views\ImageView.axaml">
      <SubType>Designer</SubType>
    </AvaloniaXaml>
    <AvaloniaXaml Update="Views\AppSettingsView.axaml">
      <SubType>Designer</SubType>
    </AvaloniaXaml>
    <AvaloniaXaml Update="Views\NoteTextView.axaml">
      <SubType>Designer</SubType>
    </AvaloniaXaml>
    <AvaloniaXaml Update="Views\MiniNoteView.axaml">
      <SubType>Designer</SubType>
    </AvaloniaXaml>
    <AvaloniaXaml Update="Views\WorkspaceView.axaml">
      <SubType>Designer</SubType>
    </AvaloniaXaml>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Views\InteractiveNoteView.axaml.cs">
      <DependentUpon>InteractiveNoteView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\NoteTextView.axaml.cs">
      <SubType>Code</SubType>
      <DependentUpon>NoteTextView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\NotesView.axaml.cs">
      <DependentUpon>NotesView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\MiniNoteView.axaml.cs">
      <SubType>Code</SubType>
      <DependentUpon>MiniNoteView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\NodeColorChangeView.axaml.cs">
      <DependentUpon>NodeColorChangeView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\SaveDialogWindowView.axaml.cs">
      <DependentUpon>SaveDialogWindowView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\WorkspaceSettingsView.axaml.cs">
      <DependentUpon>WorkspaceSettingsView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\InteractiveView.axaml.cs">
      <DependentUpon>InteractiveView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\MainContentView.axaml.cs">
      <DependentUpon>MainContentView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\ImageView.axaml.cs">
      <SubType>Code</SubType>
      <DependentUpon>ImageView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\MainWindowView.axaml.cs">
      <DependentUpon>MainWindowView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\EdgeView.axaml.cs">
      <SubType>Code</SubType>
      <DependentUpon>EdgeView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\AppSettingsView.axaml.cs">
      <SubType>Code</SubType>
      <DependentUpon>AppSettingsView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\WorkspaceView.axaml.cs">
      <SubType>Code</SubType>
      <DependentUpon>WorkspaceView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\NodeView.axaml.cs">
      <DependentUpon>NodeView.axaml</DependentUpon>
    </Compile>
  </ItemGroup>
</Project>
